### ISSUE TITLE
High WPM numbers when holding down Space or Enter

### ISSUE THREAD

**Issue by faustinozanetto** [jokarz/react-typing-game-hook#2]
Hey, I noticed that when you hold the space or enter key and not write correct words, when you finish the test the wpm are really high when they should be low or 0. Do you know what might be causing  this?. 

Thanks in advance.

**Comment by faustinozanetto** [comment]
https://codesandbox.io/s/heuristic-mccarthy-y37sg?file=/src/components/TypingInput.tsx:1898-1909 I found the issue on this demo.

**Comment by jokarz** [comment]
Hi! The high WPM is due to space/enter being taking into account for that demo. If you look at the accuracy it's pretty low since none of the letters has been entered. Thus, the hook is functioning as expected. 

That being said, would gladly accept a better ( simplistic as well ) demo to showcase more variation of using the hook!

**Comment by faustinozanetto** [comment]
Hey thanks for answering, If I have enough time I would make a more complete demo, and also thanks for making such an amazing hook. Grettings.
